export const COMPANY_SIZES = ["1-10 nhân viên", "11-50 nhân viên", "51-200 nhân viên", "201-500 nhân viên", "501-1000 nhân viên", "1001-5000 nhân viên", "5001-10,000 nhân viên", "Trên 10,000 nhân viên"];
export const MAX_IMAGE_SIZE = 5 * 1024 * 1024; // 10 megabytes
export const MIN_IMAGE_WIDTH = 50;
export const MIN_IMAGE_HEIGHT = 50;
export const MAX_IMAGE_WIDTH = 50;
export const MAX_IMAGE_HEIGHT = 50;
export const VALID_CV_TYPES = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];
export const MAX_CV_SIZE = 5 * 1024 * 1024; // 5MB
export const OptionLocation = [
    "Hà Nội",
    "Hồ Chí Minh",
    "Đà Nẵng",
    "Bình Dương",
    "Cần Thơ",
    "Khánh Hòa",
    "Đồng Nai",
    "Bà Rịa - Vũng Tàu",
    "Hải Phòng",
    "Thừa Thiên Huế",
    "Hà Giang",
    "Cao Bằng",
    "Bắc Kạn",
    "Tuyên Quang",
    "Lào Cai",
    "Điện Biên",
    "Lai Châu",
    "Sơn La",
    "Yên Bái",
    "Hoà Bình",
    "Thái Nguyên",
    "Lạng Sơn",
    "Quảng Ninh",
    "Bắc Giang",
    "Phú Thọ",
    "Vĩnh Phúc",
    "Bắc Ninh",
    "Hải Dương",
    "Hưng Yên",
    "Thái Bình",
    "Hà Nam",
    "Nam Định",
    "Ninh Bình",
    "Thanh Hóa",
    "Nghệ An",
    "Hà Tĩnh",
    "Quảng Bình",
    "Quảng Trị",
    "Quảng Nam",
    "Quảng Ngãi",
    "Bình Định",
    "Phú Yên",
    "Ninh Thuận",
    "Bình Thuận",
    "Kon Tum",
    "Gia Lai",
    "Đắk Lắk",
    "Đắk Nông",
    "Lâm Đồng",
    "Bình Phước",
    "Tây Ninh",
    "Long An",
    "Tiền Giang",
    "Bến Tre",
    "Trà Vinh",
    "Vĩnh Long",
    "Đồng Tháp",
    "An Giang",
    "Kiên Giang",
    "Hậu Giang",
    "Sóc Trăng",
    "Bạc Liêu",
    "Cà Mau"
]